export const IS_DEV = import.meta.env.NODE_ENV !== "production";

export const env = {
  ANALYTICS_ENDPOINT: import.meta.env.VITE_ANALYTICS_ENDPOINT,
  ANALYTICS_SITE_ID: import.meta.env.VITE_ANALYTICS_SITE_ID,
  APPNAME: import.meta.env.VITE_APPNAME,
  APIADDR: import.meta.env.VITE_APIADDR,
  DEVAPIADDR: import.meta.env.VITE_DEVAPIADDR,
  BASE_URL: import.meta.env.VITE_BASE_URL,
  IPFS_API_URL: import.meta.env.VITE_IPFS_API_URL,
  LOCALNODE: import.meta.env.VITE_LOCALNODE,
  NETWORK: import.meta.env.VITE_NETWORK,
  PRIVATENODE: import.meta.env.VITE_PRIVATENODE,
  MAIN_TOKEN_ADDRESS: import.meta.env.VITE_MAIN_TOKEN_ADDRESS,
  MAIN_TOKEN_NAME: import.meta.env.VITE_MAIN_TOKEN_NAME,
  MAIN_TOKEN_KEY_FOR_COIN_GECKO:
    import.meta.env.VITE_MAIN_TOKEN_KEY_FOR_COIN_GECKO,
  MINIMUM_VOTING_PERIOD: import.meta.env.VITE_MINIMUM_VOTING_PERIOD,
  MAXIMUM_VOTING_PERIOD: import.meta.env.VITE_MAXIMUM_VOTING_PERIOD,
  MINIMUM_VOTING_PERIOD_UNIT: import.meta.env.VITE_MINIMUM_VOTING_PERIOD_UNIT,
  GOVERNANCE_TOKEN_NAME: import.meta.env.VITE_GOVERNANCE_TOKEN_NAME,
  ACCRUING_TOKEN_NAME: import.meta.env.VITE_ACCRUING_TOKEN_NAME,
  ACCRUING_TOKEN_ADDRESS: import.meta.env.VITE_ACCRUING_TOKEN_ADDRESS,
  GOVERNANCE_TOKEN_CONTRACT_ADDRESS:
    import.meta.env.VITE_GOVERNANCE_TOKEN_ADDRESS,
  GOVERNANCE_CONTRACT_ADDRESS:
    import.meta.env.VITE_GOVERNANCE_CONTRACT_ADDRESS,
  GOVERNANCE_TOKEN_LOGO_ADDRESS:
    import.meta.env.VITE_GOVERNANCE_TOKEN_LOGO_ADDRESS,
  GAUGE_PROXY_ADDRESS: import.meta.env.VITE_GAUGE_PROXY_ADDRESS,
};
